### ISSUE TITLE
Getting this error, What could be the reason?

### ISSUE THREAD

**Issue by IrfanHusain** [un4gi/mBot#5] opened 2022-10-05 09:04 UTC
Bearer token expired.
2022/10/05 09:01:02 Get https://login.synack.com/: stopped after 10 redirects
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x67d588]

goroutine 1 [running]:
github.com/un4gi/mBot/auth.GetCSRFToken(0x0, 0x0, 0x0, 0x0)

**Comment by Y4h1a** [comment] 2022-10-06 19:54
Me too got this error.

**Comment by un4gi** [comment] 2022-10-11 03:36
I was getting this error also for a while, but it seems to be fixed now.

This seems to be an issue with something on the Synack end. Likely two different login pages are being hosted; one that redirects to "login.synack.com" and one with the actual expected content. 

I believe that this issue is being cause by improper redirection on the backend. Either way, the bot is working as intended. If the issue comes back again I may have to investigate ways to work around it, but for now it seems fixed.

**Closed by un4gi** 2022-10-11 03:36 UTC
Labels: bug, wontfix
